package com.quicktrade.entity;

import jakarta.persistence.*;

    @Entity
    @Table(name = "stock_names")
    public class StockNames {

        @Id
        @GeneratedValue(strategy = GenerationType.AUTO)
        private Long id; // Changed to Long for autogenerated primary keys

        @Column(name = "symbol")
        private String symbol;

        @Column(name= "logoUrl")
        private String logoUrl;

        @Column(name = "name")
        private String name;


        public Long getId() {
            return id;
        }

        public void setId(Long id) {
            this.id = id;
        }

        public String getSymbol() {
            return symbol;
        }

        public void setSymbol(String symbol) {
            this.symbol = symbol;
        }

        public String getLogoUrl() {
            return logoUrl;
        }

        public void setLogoUrl(String logoUrl) {
            this.logoUrl = logoUrl;
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }
    }

